routes/web.php
<?php

use App\Http\Controllers\Admin\EspaciosController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\CategoriesController;
use App\Http\Controllers\InicioController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Route;
// use Illuminate\Support\Facades\Hash;
// use Illuminate\Support\Facades\Broadcast;
use App\Http\Controllers\MailController;
//use App\Http\Controllers\InicioController;


//BUSQUEDA DE ESPACIOS AJAX
Route::get('select', [EspaciosController::class, 'index'])->name('select');
Route::get('admin/tickets/autocomplete', [EspaciosController::class, 'autocompleteEspacio'])->name('autocomplete');
Route::get('admin/tickets/{ticket}/autocomplete', [EspaciosController::class, 'autocompleteEspacio'])->name('autocomplete');
//BUSQUEDA USUARIOS AJAX
Route::get('admin/tickets/autocompleteuser', [UsersController::class, 'autocompleteuser'])->name('autocompleteuser');
Route::get('admin/tickets/{ticket}/autocompleteuser', [UsersController::class, 'autocompleteuser'])->name('autocompleteuser');
//BUSQUEDA SUBCATEGORIAS AJAX
//Route::get('admin/subcategories/listsubs', [SubcategoriesController::class, 'listsubs'])->name('listsubs');
Route::get('admin/tickets/listsubs/{category}', [CategoriesController::class, 'listsubs'])->name('listsubs');


Route::get('/', 'InicioController@index');
//Route::get('/','App\Http\Controllers\InicioController@index');
Route::get('/home', function () {
    $route = Gate::denies('dashboard_access') ? 'admin.tickets.index' : 'admin.home';
    if (session('status')) {
        return redirect()->route($route)->with('status', session('status'));
    }
    return redirect()->route($route);
});

Auth::routes(['register' => false]);
Route::get('sendmail', [MailController::class, 'index'])->name('sendmail');
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Statuses
    Route::delete('statuses/destroy', 'StatusesController@massDestroy')->name('statuses.massDestroy');
    Route::resource('statuses', 'StatusesController');

    // Priorities
    Route::delete('priorities/destroy', 'PrioritiesController@massDestroy')->name('priorities.massDestroy');
    Route::resource('priorities', 'PrioritiesController');

    // Categories
    Route::delete('categories/destroy', 'CategoriesController@massDestroy')->name('categories.massDestroy');
    Route::resource('categories', 'CategoriesController');
    // Subcategories
    Route::delete('subcategories/destroy', 'SubcategoriesController@massDestroy')->name('subcategories.massDestroy');
    Route::resource('subcategories', 'SubcategoriesController');

    //Edificios
    Route::delete('edificios/destroy', 'EdificiosController@massDestroy')->name('edificios.massDestroy');
    Route::resource('edificios', 'EdificiosController');

    //Espacios
    Route::delete('espacios/destroy', 'EspaciosController@massDestroy')->name('espacios.massDestroy');
    Route::resource('espacios', 'EspaciosController');

    // Tickets
    Route::delete('tickets/destroy', 'TicketsController@massDestroy')->name('tickets.massDestroy');
    Route::post('tickets/media', 'TicketsController@storeMedia')->name('tickets.storeMedia');
    Route::post('tickets/comment/{ticket}', 'TicketsController@storeComment')->name('tickets.storeComment');
    Route::resource('tickets', 'TicketsController');

    // Comments
    Route::delete('comments/destroy', 'CommentsController@massDestroy')->name('comments.massDestroy');
    Route::resource('comments', 'CommentsController');    
});

app/Models/Espacio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Espacio extends Model
{
    use HasFactory;
    protected $fillable = [
        'nomenclatura',
        'edificio_id',
        'tipoEspacio_id',
        'detalle',
        'capacidad'
    ];
    public function edificios(){
        return $this->belongsTo('App\Models\Edificio');    
    }
    public function tipoEspacios(){
        return $this->belongsTo('App\Models\tipoEspacio');
    }
    public function Ticket(){
        return $this->hasMany('App\Models\Ticket');
    }
}

app/Http/Controllers/Admin/EspaciosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Edificio;
use Illuminate\Http\Request;
use App\Models\Espacio;
use App\Models\tipoEspacio;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Symfony\Component\HttpFoundation\Response;
class EspaciosController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('espacio_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $espacios = Espacio::all();
        return view('admin.espacios.index', compact('espacios'));
    }

    public function create()
    {
        abort_if(Gate::denies('espacio_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $edificios = Edificio::all()->pluck('nombre','id');
        $tipoEspacios= tipoEspacio::all()->pluck('nombre','id');
        return view('admin.espacios.create',compact('edificios','tipoEspacios'));
    }
    public function store(Request $request)
    {
        $espacio = Espacio::create([
            'nomenclatura'  => $request->nomenclatura,
            'edificio_id'   =>$request->edificio,
            'tipoEspacio_id' =>$request->tipoespacio,
            'detalle'       =>$request->detalle,
            'capacidad'     =>$request->capacidad
        ]);
        return redirect()->route('admin.espacios.index');
    }    
    public function show($id)
    {
        //
    }

    public function edit(Espacio $espacio)
    {
        //return $espacio;
        abort_if(Gate::denies('espacio_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $edificios = Edificio::all()->pluck('nombre','id');
        $tipoEspacios= tipoEspacio::all()->pluck('nombre','id');
        return view('admin.espacios.edit',compact('espacio','edificios','tipoEspacios'));
    }
    public function update(Request $request ,Espacio $espacio)
    {
        //return $request;
            $espacio->update($request->all());
        return redirect()->route('admin.espacios.index');
    }

    
    public function destroy(Espacio $espacio)
    {   
        abort_if(Gate::denies('espacio_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        //return "prueba";
        $espacio->delete();
        return back();
    }
    public function autocompleteEspacio(Request $request)
    {
        $data = [];
        if($request->has('q')){
            $search = $request->q;
            $data = Espacio::select("id", DB::raw("CONCAT(espacios.nomenclatura,' ',espacios.detalle) AS nomenclatura"))
            ->where('nomenclatura','LIKE',"%$search%")
            ->orWhere('detalle','LIKE',"%$search%")
            ->get();
        }
        return response()->json($data);
    }
}

resources/views/admin/espacios/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.espacio.title_singular') }}
    </div>
    <div class="card-body">
        <form action="{{ route("admin.espacios.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            @include('admin.espacios.partials.form')
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection
@section('scripts')

@endsection

resources/views/admin/espacios/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.espacio.title_singular') }}
    </div>
    <div class="card-body">
        <form action="{{ route("admin.espacios.update",[$espacio->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            @include('admin.espacios.partials.form')
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection
@section('styles')
<!--link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/css/bootstrap-colorpicker.min.css" rel="stylesheet"-->
@endsection
@section('scripts')
<!--script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.5.3/js/bootstrap-colorpicker.min.js"></script-->
<script>
    //$('.colorpicker').colorpicker();
</script>
@endsection

resources/views/admin/espacios/index.blade.php
@extends('layouts.admin')
@section('content')
@can('espacio_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.espacios.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.espacio.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.espacio.title_singular') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-Espacio">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.espacio.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.espacio.fields.nomenclatura') }}
                        </th>
                        <th>
                            {{ trans('cruds.espacio.fields.detalle') }}
                        </th>
                        <th>
                            {{ trans('cruds.espacio.fields.capacidad') }}
                        </th>
                       
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($espacios as $key => $espacio)
                        <tr data-entry-id="{{ $espacio->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $espacio->id ?? '' }}
                            </td>
                            <td>
                                {{ $espacio->nomenclatura ?? '' }}
                            </td>
                            <td>
                                {{ $espacio->detalle ?? '' }}
                            </td>
                            <td>
                                {{ $espacio->capacidad ?? '' }}
                            </td>
                            <!--td style="background-color:{{ $espacio->color ?? '#FFFFFF' }}"></td-->
                            <td>
                                @can('espacio_show')
                                    <!--a class="btn btn-xs btn-primary" href="{{ route('admin.espacios.show', $espacio->id) }}">
                                        {{ trans('global.view') }}
                                    </a-->
                                @endcan

                                @can('espacio_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.espacios.edit', $espacio->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('espacio_delete')
                                    <form action="{{ route('admin.espacios.destroy', $espacio->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
$(function () {
    let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
    @can('espacio_delete')
        let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
        let deleteButton = {
            text: deleteButtonTrans,
            url: "{{ route('admin.espacios.massDestroy') }}",
            className: 'btn-danger',
            action: function (e, dt, node, config) {
                var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
                    return $(entry).data('entry-id')
            });
                if (ids.length === 0) {
                    alert('{{ trans('global.datatables.zero_selected') }}')
                    return
                }

                if (confirm('{{ trans('global.areYouSure') }}')) {
                    $.ajax({
                        headers: {'x-csrf-token': _token},
                        method: 'POST',
                        url: config.url,
                        data: { ids: ids, _method: 'DELETE' }})
                        .done(function () { location.reload() })
                }
            }
        }
        dtButtons.push(deleteButton)
    @endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-Espacio:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})
</script>
@endsection